### ISSUE TITLE
Some volume mount not found

### ISSUE THREAD

**Issue by kamniphat** [getindata/apache-nifi-kubernetes#3]
Hi, 
When statefulsets initial i hit this error "**StatefulSet nifi failed error: Pod "nifi-0" is invalid: [spec.containers[0].volumeMounts[4].name: Not found: "nifi-extensions", spec.containers[0].volumeMounts[11].name: Not found: "krb5-temp", spec.containers[0].volumeMounts[12].name: Not found: "jdk-link"]**"  

may i know anyone know how to fix this?

**Comment by albertlewandowski** [comment]
Hi @kamniphat, I'll commit fix today afternoon.

**Comment by kamniphat** [comment]
Thanks @albertlewandowski
